---
title: "Homework 6"
author: "Yifei Xu"
date: "2022-12-02"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

### Problem 0 

First, create a subdirectory to store the local data files used in the assignment.

```{r}
dir.create(file.path(getwd(), "hw6_data_file"), recursive = TRUE)
```

### Problem 2

First, import the dataset from the GitHub repository.

```{r, message=FALSE}
data_url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

homicide = read_csv(url(data_url)) 
```

Second, clean the dataset as required.

```{r, message=FALSE}
homicide_tidy = homicide %>%
  janitor::clean_names() %>%
  mutate(reported_date = as.Date(as.character(reported_date), format = "%Y%m%d")) %>% 
  mutate(city_state = str_c(city, state, sep = ", "), 
         resolved= case_when(disposition == "Closed by arrest" ~ "solved",
                                disposition == "Closed without arrest" ~ "unsolved",
                                disposition == "Open/No arrest" ~ "unsolved")) %>% 
  select(city_state, everything()) %>%
  filter(!city_state %in% c("Tulsa, AL", "Dallas, TX", "Phoenix, AZ", "Kansas City, MO")) %>%
  filter(victim_race %in% c("White", "Black")) %>%
  mutate(victim_age = as.numeric(victim_age))

```

Third, fit a logistic regression.




